//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp32ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_m_supplier()
        {
            this.tb_m_items = new HashSet<tb_m_items>();
        }

        //public tb_m_supplier(string name, string email)
        //{
        //    this.Name = name;
        //    this.Email = email;
        //    this.CreateDate = DateTimeOffset.Now.LocalDateTime;
        //}

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_m_items> tb_m_items { get; set; }
    }
}
